
ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY';
-- 1. Chức năng
CREATE TABLE CHUC_NANG
(
    MaChucNang  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChucNang NVARCHAR2(255) NOT NULL
);

-- 2. Người dùng
CREATE TABLE NGUOI_DUNG
(
    MaNguoiDung   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HoTen         NVARCHAR2(255)       NOT NULL,
    Email         VARCHAR2(100) UNIQUE NOT NULL,
    AnhDaiDienURL VARCHAR2(500),
    SoDienThoai   VARCHAR2(15) UNIQUE  NOT NULL,
    DaXacThuc     NUMBER(1) DEFAULT 0 NOT NULL CHECK (DaXacThuc IN (0, 1)),
    NgayTao       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Địa điểm
CREATE TABLE DIA_DIEM
(
    MaDiaDiem     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenDiaDiem    NVARCHAR2(255) NOT NULL,
    SucChua       NUMBER(6, 0)  DEFAULT 0 NOT NULL CHECK (SucChua >= 0),
    TinhThanh     NVARCHAR2(255) NOT NULL,
    PhuongXa      NVARCHAR2(255) NOT NULL,
    SoNhaTenDuong NVARCHAR2(255) NOT NULL
);

-- 4. Nhà tài trợ
CREATE TABLE NHA_TAI_TRO
(
    MaNhaTT  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhaTT NVARCHAR2(255) NOT NULL
);

-- 5. Nhóm quyền
CREATE TABLE NHOM_QUYEN
(
    MaNhomQuyen  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNhomQuyen NVARCHAR2(100) NOT NULL,
    MoTa         CLOB
);

-- 6. Nghệ sĩ
CREATE TABLE NGHE_SI
(
    MaNgheSi      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenNgheSi     NVARCHAR2(255) NOT NULL,
    Email         VARCHAR2(100) UNIQUE,
    AnhDaiDienURL VARCHAR2(500),
    SoDienThoai   VARCHAR2(15) UNIQUE
);

-- 7. Chiến dịch khuyến mãi
CREATE TABLE CHIEN_DICH_KHUYEN_MAI
(
    MaChienDich  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenChienDich NVARCHAR2(255) NOT NULL,
    ThoiDiemBD   TIMESTAMP      NOT NULL,
    ThoiDiemKT   TIMESTAMP      NOT NULL,
    TrangThai    NVARCHAR2(50) DEFAULT N'Chưa diễn ra' NOT NULL CHECK (TrangThai IN (N'Chưa diễn ra', N'Đang diễn ra', N'Tạm dừng', N'Đã kết thúc')),
    CONSTRAINT CK_CHIEN_DICH_TIME CHECK (ThoiDiemBD < ThoiDiemKT)
);

-- 8. Tài khoản
CREATE TABLE TAI_KHOAN
(
    MaTaiKhoan         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguoiDung        NUMBER REFERENCES NGUOI_DUNG (MaNguoiDung),
    TenDangNhap        VARCHAR2(100) UNIQUE NOT NULL,
    MatKhauMaHoa       VARCHAR2(255)        NOT NULL,
    TrangThai          NVARCHAR2(50) DEFAULT N'Hoạt động' NOT NULL CHECK (TrangThai IN (N'Hoạt động', N'Bị khóa', N'Bị cấm')),
    LanDangNhapCuoi    TIMESTAMP,
    DongYNhanMarketing NUMBER(1) DEFAULT 0 CHECK (DongYNhanMarketing IN (0, 1))
);

-- 9. Nhà tổ chức
CREATE TABLE NHA_TO_CHUC
(
    MaNhaToChuc      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNguoiDaiDien   NUMBER REFERENCES NGUOI_DUNG (MaNguoiDung),
    MaTaiKhoan       NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenNhaToChuc     NVARCHAR2(255)      NOT NULL,
    MaSoThue         VARCHAR2(50) UNIQUE NOT NULL,
    ThongTinNganHang NVARCHAR2(255)      NOT NULL,
    EmailHoTro       VARCHAR2(100)
);

-- 10. Ví cá nhân
CREATE TABLE VI_CA_NHAN
(
    MaVi             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan       NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    SoDu             NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (SoDu >= 0),
    MatKhauThanhToan VARCHAR2(255)           NOT NULL,
    TrangThai        NVARCHAR2(50) DEFAULT N'Đang hoạt động' NOT NULL CHECK (TrangThai IN (N'Bị khóa', N'Đang hoạt động'))
);

-- 11. Mẫu chính sách hoàn tiền
CREATE TABLE MAU_CHINH_SACH_HOAN_TIEN
(
    MaChinhSachHT NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan    NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenChinhSach  NVARCHAR2(255) NOT NULL,
    MoTa          CLOB
);

-- 12. Phạm vi quyền
CREATE TABLE PHAM_VI_QUYEN
(
    MaPhamVi   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaChucNang NUMBER REFERENCES CHUC_NANG (MaChucNang),
    Them       NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Them BETWEEN 0 AND 1),
    Sua        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Sua BETWEEN 0 AND 1),
    Xoa        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Xoa BETWEEN 0 AND 1),
    Xem        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (Xem BETWEEN 0 AND 1),
    XuatFile   NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (XuatFile BETWEEN 0 AND 1)
);

-- 13. Mã giảm giá
CREATE TABLE MA_GIAM_GIA
(
    ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaChienDich    NUMBER REFERENCES CHIEN_DICH_KHUYEN_MAI (MaChienDich),
    MaGiamGia      VARCHAR2(50) UNIQUE NOT NULL,
    LoaiGiam       NVARCHAR2(50) DEFAULT N'Theo phần trăm' NOT NULL CHECK (LoaiGiam IN (N'Theo phần trăm', N'Số tiền cố định')),
    SoLuongGiam    NUMBER(15, 2)       NOT NULL CHECK (SoLuongGiam >= 0),
    GiamToiDa      NUMBER(15, 2)       NOT NULL CHECK (GiamToiDa >= 0),
    LuotDungToiDa  NUMBER(10) NOT NULL CHECK (LuotDungToiDa >= 0),
    SoLuotDaSuDung NUMBER(10) DEFAULT 0 CHECK (SoLuotDaSuDung >= 0),
    CONSTRAINT CK_GIAM_GIA_LIMIT CHECK (SoLuotDaSuDung <= LuotDungToiDa),
    CONSTRAINT CK_LG_THEO_PHAN_TRAM CHECK ((LoaiGiam = N'Theo phần trăm' AND SoLuongGiam <= 100) OR
                                           LoaiGiam = N'Số tiền cố định' ),
    CONSTRAINT CK_GIAM_TOI_DA CHECK ((LoaiGiam = N'Số tiền cố định' AND SoLuongGiam <= GiamToiDa) OR LoaiGiam = N'Theo phần trăm')
);

-- 14. Quy tắc hoàn tiền
CREATE TABLE QUY_TAC_HOAN_TIEN
(
    MaQuyTac         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaChinhSachHT    NUMBER REFERENCES MAU_CHINH_SACH_HOAN_TIEN (MaChinhSachHT),
    SoGioTruocSuKien NUMBER(10) NOT NULL CHECK (SoGioTruocSuKien >= 0),
    TyLeHoanTien     NUMBER(5, 2) DEFAULT 0 NOT NULL CHECK (TyLeHoanTien BETWEEN 0 AND 100)
);

-- 15. Cấu hình nhóm quyền
CREATE TABLE CAU_HINH_NHOM_QUYEN
(
    MaNhomQuyen NUMBER REFERENCES NHOM_QUYEN (MaNhomQuyen),
    MaPhamVi    NUMBER REFERENCES PHAM_VI_QUYEN (MaPhamVi),
    PRIMARY KEY (MaNhomQuyen, MaPhamVi)
);

-- 16. Phân quyền nhóm
CREATE TABLE PHAN_QUYEN_NHOM
(
    MaTaiKhoan  NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaNhomQuyen NUMBER REFERENCES NHOM_QUYEN (MaNhomQuyen),
    PRIMARY KEY (MaTaiKhoan, MaNhomQuyen)
);

-- 17. Phân quyền tài khoản
CREATE TABLE PHAN_QUYEN_TAI_KHOAN
(
    MaTaiKhoan NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaPhamVi   NUMBER REFERENCES PHAM_VI_QUYEN (MaPhamVi),
    PRIMARY KEY (MaTaiKhoan, MaPhamVi)
);

-- 18. Sự kiện
CREATE TABLE SU_KIEN
(
    MaSuKien           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDiaDiem          NUMBER REFERENCES DIA_DIEM (MaDiaDiem),
    MaChinhSachHT      NUMBER REFERENCES MAU_CHINH_SACH_HOAN_TIEN (MaChinhSachHT),
    MaNhaToChuc        NUMBER REFERENCES NHA_TO_CHUC (MaNhaToChuc),
    TenSuKien          NVARCHAR2(255) NOT NULL,
    ThoiGianBD         TIMESTAMP      NOT NULL,
    ThoiGianKT         TIMESTAMP      NOT NULL,
    ThoiGianMoBanVe    TIMESTAMP      NOT NULL,
    ThoiGianNgungBanVe TIMESTAMP      NOT NULL,
    MoTa               CLOB,
    TrangThai          NVARCHAR2(50) DEFAULT N'Chờ phê duyệt' NOT NULL CHECK (TrangThai IN
                                            (N'Chờ phê duyệt', N'Sắp diễn ra', N'Đang diễn ra', N'Đã kết thúc', N'Đã hủy')),
    TyLeHoaHong        NUMBER(5, 2) DEFAULT 0 NOT NULL CHECK (TyLeHoaHong BETWEEN 0 AND 100),
    QuyDinhSuKien      CLOB,
    CONSTRAINT CK_SK_TGSK CHECK (ThoiGianBD < ThoiGianKT),
    CONSTRAINT CK_SK_TGBV CHECK (ThoiGianMoBanVe < ThoiGianNgungBanVe),
    CONSTRAINT CK_SK_TGBV_TGBD CHECK (ThoiGianMoBanVe < ThoiGianBD),
    CONSTRAINT CK_SK_TGNBV_TGKT CHECK (ThoiGianNgungBanVe <= ThoiGianKT)
);

-- 19. Tài trợ
CREATE TABLE TAI_TRO
(
    MaSuKien   NUMBER REFERENCES SU_KIEN (MaSuKien),
    MaNhaTT    NUMBER REFERENCES NHA_TAI_TRO (MaNhaTT),
    HangTaiTro NVARCHAR2(50) DEFAULT N'Đồng' NOT NULL CHECK (HangTaiTro IN (N'Đồng', N'Bạc', N'Vàng', N'Kim Cương')),
    PRIMARY KEY (MaSuKien, MaNhaTT)
);

-- 20. Tham gia
CREATE TABLE THAM_GIA
(
    MaNgheSi    NUMBER REFERENCES NGHE_SI (MaNgheSi),
    MaSuKien    NUMBER REFERENCES SU_KIEN (MaSuKien),
    VaiTroChinh NVARCHAR2(100),
    PRIMARY KEY (MaNgheSi, MaSuKien)
);
-- 21. Hạng vé
CREATE TABLE HANG_VE
(
    MaHangVe        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaSuKien        NUMBER REFERENCES SU_KIEN (MaSuKien),
    TenHangVe       NVARCHAR2(100) NOT NULL,
    GiaNiemYet      NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (GiaNiemYet >= 0),
    TongSoLuong     NUMBER(10) CHECK (TongSoLuong >= 0),
    GioiHanMoiNguoi NUMBER(5) CHECK (GioiHanMoiNguoi >= 0),
    MoTa            CLOB
);

-- 22. Khu vực
CREATE TABLE KHU_VUC
(
    MaKhuVuc  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaHangVe  NUMBER REFERENCES HANG_VE (MaHangVe),
    TenKhuVuc NVARCHAR2(255) NOT NULL,
    SucChuaKV NUMBER(10)     NOT NULL CHECK (SucChuaKV >= 0),
    MoTaKV    CLOB
);

-- 23. Lịch diễn
CREATE TABLE LICH_DIEN
(
    MaLichDien        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TenLichDien       NVARCHAR2(255) NOT NULL,
    TrangThaiLichDien NVARCHAR2(50) DEFAULT N'Chưa diễn ra' NOT NULL CHECK (TrangThaiLichDien IN (N'Chưa diễn ra', N'Đang diễn ra', N'Đã kết thúc')),
    MaSuKien          NUMBER REFERENCES SU_KIEN (MaSuKien),
    ThoiGianBatDau    TIMESTAMP      NOT NULL,
    ThoiGianKetThuc   TIMESTAMP      NOT NULL,
    TrangThaiBanVe    NVARCHAR2(50) DEFAULT N'Còn vé' NOT NULL CHECK (TrangThaiBanVe IN (N'Còn vé', N'Hết vé')),
    CONSTRAINT CK_SUAT_DIEN_TIME CHECK (ThoiGianBatDau < ThoiGianKetThuc)
);

-- 24. Phân công sự kiện nhân viên
CREATE TABLE PHAN_CONG_SK_NV
(
    MaTaiKhoan NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaSuKien   NUMBER REFERENCES SU_KIEN (MaSuKien),
    PRIMARY KEY (MaTaiKhoan, MaSuKien)
);

-- 25. Đơn mua
CREATE TABLE DON_MUA
(
    MaDonMua            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan          NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaSuKien            NUMBER REFERENCES SU_KIEN (MaSuKien),
    ThoiDiemMua         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TongTien            NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (TongTien >= 0),
    TrangThaiThanhToan  NVARCHAR2(50) DEFAULT N'Chờ thanh toán' NOT NULL CHECK (TrangThaiThanhToan IN
                                             (N'Chờ thanh toán', N'Đã thanh toán', N'Đã hủy', N'Đã hoàn tiền', N'Đã hết hạn')),
    PhuongThucThanhToan NVARCHAR2(100)
);

-- 26. Ghế ngồi
CREATE TABLE GHE_NGOI
(
    MaGhe    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaKhuVuc NUMBER REFERENCES KHU_VUC (MaKhuVuc),
    ToaDo    VARCHAR2(100) NOT NULL,
    CONSTRAINT UNQ_GHE_KV UNIQUE (MaKhuVuc, ToaDo)
);

-- 27. Trạng thái ghế theo suất
CREATE TABLE TRANG_THAI_GHE_THEO_SUAT
(
    MaGhe      NUMBER REFERENCES GHE_NGOI (MaGhe),
    MaLichDien NUMBER REFERENCES LICH_DIEN (MaLichDien),
    TrangThai  NVARCHAR2(50) DEFAULT N'Còn trống' NOT NULL CHECK (TrangThai IN (N'Còn trống', N'Đã đặt', N'Đang giữ chỗ')),
    PRIMARY KEY (MaGhe, MaLichDien)
);

-- 28. Áp dụng
CREATE TABLE AP_DUNG
(
    MaDonMua         NUMBER REFERENCES DON_MUA (MaDonMua),
    IDGiamGia        NUMBER REFERENCES MA_GIAM_GIA (ID),
    ThoiDiemApDung   TIMESTAMP DEFAULT CURRENT_TIMESTAMP         NOT NULL,
    SoTienGiamThucTe NUMBER(15, 2) CHECK (SoTienGiamThucTe >= 0) NOT NULL,
    PRIMARY KEY (MaDonMua, IDGiamGia)
);

-- 29. Giao dịch
CREATE TABLE GIAO_DICH
(
    MaGiaoDich       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua         NUMBER REFERENCES DON_MUA (MaDonMua),
    MaGiaoDichCongTT VARCHAR2(100),
    SoTien           NUMBER(15, 2) DEFAULT 0 NOT NULL CHECK (SoTien >= 0),
    TrangThai        NVARCHAR2(50) DEFAULT N'Chờ thanh toán' NOT NULL CHECK (TrangThai IN (N'Chờ thanh toán', N'Thành công', N'Thất bại')),
    MaLoi            VARCHAR2(50),
    DuLieuPhanHoi    CLOB,
    ThoiGianTao      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CK_MA_LOI_NOT_NULL CHECK (TrangThai <> N'Thất bại' OR MaLoi IS NOT NULL)
);

-- 30. Lịch sử biến động ví
CREATE TABLE LICH_SU_BIEN_DONG_VI
(
    MaBienDong         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaVi               NUMBER REFERENCES VI_CA_NHAN (MaVi),
    MaGiaoDichLienQuan NUMBER REFERENCES GIAO_DICH (MaGiaoDich),
    LoaiBienDong       NVARCHAR2(50) NOT NULL CHECK (LoaiBienDong IN (N'Tăng', N'Giảm')),
    SoTien             NUMBER(15, 2) CHECK (SoTien >= 0),
    NoiDung            NVARCHAR2(500),
    ThoiGian           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 31. Vé
CREATE TABLE VE
(
    MaVe            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua        NUMBER REFERENCES DON_MUA (MaDonMua),
    MaHangVe        NUMBER REFERENCES HANG_VE (MaHangVe),
    MaGhe           NUMBER REFERENCES GHE_NGOI (MaGhe),
    MaLichDien      NUMBER REFERENCES LICH_DIEN (MaLichDien),
    DaBanLai        NUMBER(1, 0) DEFAULT 0 NOT NULL CHECK (DaBanLai IN (0, 1)),
    GiaBanLai       NUMBER(15, 2) CHECK (GiaBanLai >= 0),
    LinkQRCode      VARCHAR2(500),
    TrangThaiVe     VARCHAR2(50) DEFAULT N'Hiệu lực' NOT NULL CHECK (TrangThaiVe IN (N'Hiệu lực', N'Đã Check-in', N'Đã hủy', N'Chờ thanh toán')),
    ThoiGianDaBan   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    ThoiGianCheckIn TIMESTAMP,
    CONSTRAINT CK_VE CHECK ((DaBanLai = 0 AND TrangThaiVe IN (N'Đã Check-in', N'Đã hủy')) OR
                            (DaBanLai = 1 AND TrangThaiVe = N'Hiệu lực')),
    CONSTRAINT CK_TGCKIN CHECK (TrangThaiVe <> N'Đã Check-in' OR ThoiGianCheckIn IS NOT NULL),
    CONSTRAINT CK_BAN_LAI CHECK ((DaBanLai = 1 AND GiaBanLai > 0) OR (DaBanLai = 0)),
    CONSTRAINT CK_TGCKIN_TGDB CHECK (ThoiGianCheckIn >= ThoiGianDaBan)
);

-- 32. Nhật ký soát vé
CREATE TABLE NHAT_KY_SOAT_VE
(
    MaSoatVe        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan      NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaVe            NUMBER REFERENCES VE (MaVe),
    TrangThaiSoatVe NUMBER(1) DEFAULT 0 NOT NULL CHECK (TrangThaiSoatVe IN (0, 1)),
    ThoiGianQuetMa  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ThietBiQuet     VARCHAR2(255)                       NOT NULL
);

-- 33. Yêu cầu hỗ trợ
CREATE TABLE YEU_CAU_HO_TRO
(
    MaYeuCau       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua       NUMBER REFERENCES DON_MUA (MaDonMua),
    MaTaiKhoan     NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    MaNhanVienXuLy NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    LoaiYeuCau     NVARCHAR2(100) NOT NULL CHECK (LoaiYeuCau IN (N'Hoàn tiền', N'Lỗi thanh toán', N'Thay đổi thông tin', N'Lỗi vé', N'Khiếu nại', N'Khác')),
    NoiDung        CLOB,
    ThoiDiemYeuCau TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThaiXuLy  NVARCHAR2(50) DEFAULT N'Chờ phản hồi' NOT NULL CHECK (TrangThaiXuLy IN (N'Đang xử lý', N'Chờ phản hồi', N'Đã xử lý')),
    CONSTRAINT CK_YCHT_STAFF_DIFF CHECK (MaNhanVienXuLy IS NULL OR MaNhanVienXuLy <> MaTaiKhoan)
);

-- 34. Lịch sử quyết toán
CREATE TABLE LICH_SU_QUYET_TOAN
(
    MaQT             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaNhaToChuc      NUMBER REFERENCES NHA_TO_CHUC (MaNhaToChuc),
    KyQT             VARCHAR2(100),
    NgayQuyetToan    DATE DEFAULT CURRENT_DATE NOT NULL,
    TongDoanhThu     NUMBER(15, 2) CHECK (TongDoanhThu >= 0),
    PhiNenTang       NUMBER(15, 2) CHECK (PhiNenTang >= 0),
    SoTienChuyen     NUMBER(15, 2) CHECK (SoTienChuyen >= 0),
    ChungTuThanhToan VARCHAR2(500),
    TrangThai        NVARCHAR2(50) DEFAULT N'Đang xử lý' NOT NULL CHECK (TrangThai IN (N'Đã xử lý', N'Đang xử lý', N'Đã hủy'))
);

-- 35. Nhật ký hệ thống
CREATE TABLE NHAT_KY_HE_THONG
(
    MaNhatKyHT       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan       NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    HanhDong         NVARCHAR2(100),
    TenBang          NVARCHAR2(50),
    MaDoiTuong       NUMBER,
    DuLieuCu         CLOB,
    DuLieuMoi        CLOB,
    LyDo             VARCHAR2(500),
    ThoiDiemThucHien TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 36. Nhật ký thông báo
CREATE TABLE NHAT_KY_THONG_BAO
(
    MaThongBao   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaDonMua     NUMBER REFERENCES DON_MUA (MaDonMua),
    MaTaiKhoan   NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    KenhGui      NVARCHAR2(50) NOT NULL CHECK (KenhGui IN ('EMAIL', 'SMS', 'ZALO')),
    NoiDung      CLOB,
    TrangThai    NVARCHAR2(50) DEFAULT N'Đã gửi' NOT NULL CHECK (TrangThai IN (N'Đã gửi', N'Thất bại', N'Đã nhận', N'Đã xem')),
    ThoiDiemGui  TIMESTAMP NOT NULL,
    ThoiDiemNhan TIMESTAMP,
    CONSTRAINT CK_TDNHAN CHECK (ThoiDiemNhan >= ThoiDiemGui)
);

-- 37. Nhật ký đăng nhập
CREATE TABLE NHAT_KY_DANG_NHAP
(
    MaLog              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan         NUMBER REFERENCES TAI_KHOAN (MaTaiKhoan),
    TenDangNhapNhapVao VARCHAR2(100),
    ThoiGian           TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TrangThai          NVARCHAR2(50) NOT NULL CHECK(TrangThai IN (N'Thành công', N'Thất bại')),
    LyDoThatBai        VARCHAR2(255),
    DiaChiIP           VARCHAR2(45),
    UserAgent          VARCHAR2(500)
);

-- 38. TOKEN Tài khoản
CREATE TABLE TOKEN_TAI_KHOAN
(
    MaToken       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MaTaiKhoan    NUMBER NOT NULL,
    GiaTriToken   VARCHAR2(500) UNIQUE NOT NULL,
    ThoiDiemHetHan TIMESTAMP NOT NULL,
    ThoiDiemCap    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DaThuHoi      NUMBER(1) DEFAULT 0 NOT NULL CHECK (DaThuHoi IN (0, 1)),
    CONSTRAINT FK_TOKEN_TAI_KHOAN FOREIGN KEY (MaTaiKhoan) REFERENCES TAI_KHOAN (MaTaiKhoan)
);

